apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  # tolerations:
  # - key: "project"
  #   operator: "Equal"
  #   value: "expense"
  #   effect: "NoSchedule"